# This is a basic workflow to help you get started with Actions

name: Update Visualizations

on:
  workflow_dispatch:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  update_visualizations:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update visualizations
        run: python update_visualizations.py statistics
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5
        with:
          message: "Update visualizations"
          
    
